# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bikemate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bikemate

  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Kingfisher'
  pod 'ObjectMapper'
  pod 'SnapKit'
  pod 'Then'
  pod 'Alamofire'
  pod 'RxSwift', '~> 5.1.1'
  pod 'RxCocoa'
  pod 'NMapsMap'








end
